# Generated by Django 2.0.7 on 2018-09-15 21:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Condition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature', models.CharField(max_length=100)),
                ('humidity', models.CharField(max_length=100)),
                ('pH', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Dataset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inside_temperature', models.IntegerField()),
                ('inside_humidity', models.IntegerField()),
                ('outside_temperature', models.IntegerField()),
                ('outside_humidity', models.IntegerField()),
                ('water_temperature', models.IntegerField()),
                ('water_pH', models.IntegerField()),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('image', models.TextField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Grow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('end_date', models.DateTimeField(null=True)),
                ('description', models.TextField(max_length=200)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MIPI_Grow.Category')),
            ],
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Variety',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MIPI_Grow.Category')),
            ],
        ),
        migrations.AddField(
            model_name='grow',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MIPI_Grow.Type'),
        ),
        migrations.AddField(
            model_name='grow',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='grow',
            name='variety',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MIPI_Grow.Variety'),
        ),
        migrations.AddField(
            model_name='dataset',
            name='grow',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MIPI_Grow.Grow'),
        ),
        migrations.AddField(
            model_name='condition',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MIPI_Grow.Type'),
        ),
        migrations.AddField(
            model_name='condition',
            name='variety',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MIPI_Grow.Variety'),
        ),
    ]
