# Generated by Django 2.0.7 on 2018-09-07 20:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dataset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grow', models.CharField(max_length=50)),
                ('inside_temperature', models.CharField(max_length=50)),
                ('inside_humidity', models.CharField(max_length=50)),
                ('outside_temperature', models.CharField(max_length=50)),
                ('outside_humidity', models.CharField(max_length=50)),
                ('water_temperature', models.CharField(max_length=50)),
                ('water_pH', models.CharField(max_length=50)),
                ('image', models.CharField(max_length=50)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
